version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dep_cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dep_cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test